# Definition
A core library for scientific and numerical computing in python
- provides tools for working with arrays
## Its multidimentional array
- A table of elememts usually numbers, all of the same type
- dimentions are also called axes
## Array/ axes shapes(array description)
- shape(1,4) implies one array, 4 elements or simply shape(6)
- shape(3,6) implies one array, 6 elements@
## NumPy array vs Python List
-faster
-Convinient
-Less memory
- simply Numpy array is better

## personal experience 
- With NumPy, you create advanced lists/arrays like those in Matlab on which you can do advanced operations

In [2]:
import numpy as np

#creating a NumPy array
a = np.array([1,2,3])#notice, we put like a python list inside
#a is a Numpy array instance
a


array([1, 2, 3])

In [6]:
%time
a[-1]

Wall time: 0 ns


3

In [25]:
#2x3 array
array1 = np.array([[1,2,3],[4,5,6]])
array1 #output the array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.shape(array1) #state the shape of the array

(2, 3)

In [27]:
#or
array1.shape

(2, 3)

In [30]:
#change data
array2 = np.array([[1,2,3],[4,5,6]], dtype=np.float)
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
array2.itemsize

8

In [44]:
array3 = np.ones((3,2)) #like matlab, dont forget the double brackets
array3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
#the arange function
#automatically generate an array of a specified range
array4 = np.arange(4)
array4

array([0, 1, 2, 3])

In [52]:
#performing operations on characters
#use "np.char."
array5 = ["will","emox","ejulu"]
array6 = ["junior", "eliza","emma"]
array7 = np.char.add(array5,array6)
array7

array(['willjunior', 'emoxeliza', 'ejuluemma'], dtype='<U11')

In [69]:
array8 = np.char.center("hello", 40, fillchar = ".")
print(array8)

.................hello..................


In [74]:
y = np.char.upper("wilson")
print(y)

WILSON
